ARG BASE_IMAGE=nb:latest

FROM $BASE_IMAGE

# add in conda-forge and hstcal
RUN \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict

# install all the packages we could want
COPY \
    environment_everything.txt \
    requirements_everything.txt \
    /tmp/
RUN conda install --file /tmp/environment_everything.txt
RUN pip install --requirement /tmp/requirements_everything.txt
