FROM nb

# install a base set of packages; we want the latest of each
RUN \
    pip install \
        astropy \
        astroquery \
        calcos \
        ccdproc \
        crds \
        drizzlepac \
        k2flix \
        lightkurve \
        matplotlib \
        regions \
        requests \
        scipy \
        specutils \
        synphot \
        webbpsf
